### ISSUE TITLE
Side drawer not working in iOS

### ISSUE THREAD

**Issue by nutanlade** [shripalsoni04/nativescript-angular-drawer-template#12] opened 2017-03-16 03:39 UTC
I developed using basic template and it is working but after few changes to page it stopped working.
Changes done to existing code is below
1) Changed home page to enter user name and password
2) After entering details routing to dashboard
Home page code
```
<ActionBar title="Guwha" style="background-color:#22D1E4">
    
</ActionBar>

<StackLayout>
  <Image src="res://logo_signup" stretch="none" horizontalAlignment="center"></Image>
  <TextField hint="Email Address" keyboardType="email" [(ngModel)]="user.email"
    autocorrect="false" autocapitalizationType="none" class="loginTextField" verticalAlignment="center"></TextField>
  <TextField hint="Password" secure="true" [(ngModel)]="user.password" class="loginTextField" verticalAlignment="center"></TextField>
  <Button text ="Sign In"  class="submit-button" (tap)="login()"></Button> 
</StackLayout>
```
Home component code
```
login() { 
      this.userService.login(this.user)    
    .subscribe(
          () => {
            this.router.navigate(["/dashboard"],  { clearHistory: true })
          },
          () => alert("Unfortunately we could not find your account.")
        ); 
    }
```
Dashboard code 

```
<side-drawer-page>
  <ActionBar style="background-color:#22D1E4"> 
        Dashboard    
  </ActionBar>
     <Label text= "Welcome to Dashboard in Dashboard" verticalAlignment="center" horizontalAlignment="center" style="color:#22D1E4"></Label> 
<side-drawer-page>
```
When clicking in menu button side drawer is not opening. Please help me in resolving this issue.

![img_6348](https://cloud.githubusercontent.com/assets/5775600/23980733/9b7070a0-0a27-11e7-95e9-63d003793960.PNG)
![img_6347](https://cloud.githubusercontent.com/assets/5775600/23980732/9b704d28-0a27-11e7-8535-20a71a40a854.PNG)

**Comment by shripalsoni04** [comment] 2017-05-28 14:44
@nutanlade , I have published new version v2.0.0 with angular (~4.0), nativescript (~3.0) and nativescript-telerik-ui (~2.0) versions. 

I created a sample project with this template and tried to put button to navigate to other page on iOS and it seems to be working perfectly fine. Check below demo of your use case.

![ns-ng-drawer-issue 12](https://cloud.githubusercontent.com/assets/4411891/26529666/db66cb16-43e1-11e7-975e-3863d56a3e2e.gif)

It seems that the issue is resolved with latest versions. I am closing this issue as it is working fine. Feel free to reopen it if you still face it.

**Closed by shripalsoni04** 2017-05-28 14:44 UTC
